CREATE TABLE t_orders (
    id int NOT NULL AUTO_INCREMENT,
    shipping_fee decimal(10,2) NOT NULL,
    subtotal decimal(10,2) NOT NULL,
    grand_total decimal(10,2) NOT NULL,
    address_apartment varchar(255) NOT NULL,
    address_neighborhood varchar(255) NOT NULL,
    address_number varchar(255) DEFAULT NULL,
    address_street_name varchar(255) NOT NULL,
    address_zip_code varchar(255) NOT NULL,
    address_city_id int NOT NULL,
    restaurant_id int NOT NULL,
    payment_method_id int NOT NULL,
    user_id int NOT NULL,
    status varchar(9) NOT NULL,
    confirmed_at datetime NULL,
    delivered_at datetime NULL,
    canceled_at datetime NULL,
    created_at datetime NULL,
    PRIMARY KEY (id),
    KEY restaurant_id (restaurant_id),
    KEY user_id (user_id),
    KEY payment_method_id (payment_method_id),
    CONSTRAINT t_orders_ibfk_1 FOREIGN KEY (restaurant_id) REFERENCES t_restaurants (id),
    CONSTRAINT t_orders_ibfk_2 FOREIGN KEY (user_id) REFERENCES t_users (id),
    CONSTRAINT t_orders_ibfk_3 FOREIGN KEY (payment_method_id) REFERENCES t_payment_methods (id),
    CONSTRAINT t_orders_ibfk_4 FOREIGN KEY (address_city_id) REFERENCES t_cities (id)
)